FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y postgresql-client

RUN python3 -m pip install pip --upgrade
RUN pip install --upgrade setuptools

RUN mkdir -p /app

WORKDIR /app

ADD backend/requirements.txt /app
RUN pip install -r requirements.txt

ADD backend/start.sh /app

ADD backend /app/

EXPOSE 8000

CMD /app/start.sh