# Generated by Django 4.1.6 on 2023-02-12 17:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("price", models.FloatField(default=0)),
                ("score", models.IntegerField(default=0)),
                ("image", models.CharField(max_length=120)),
            ],
        ),
    ]
